### ISSUE TITLE
Get the stuff from Pedro into the docs.

### ISSUE THREAD

**Issue by griswaldbrooks** [cclrobotics/lhr-docs#1]
On 7/16/16 we talked to Pedro over Skype and he answered a bunch of LHR questions.
@tamarum Is going to type up the notes.
@ZenSpiders is going to get the pictures into the docs.
-  [x] @tamarum  should update this ticket with stuff to put in.
-  [x] @ZenSpiders should update this ticket with things to put it.

**Comment by tamarum** [comment]
Typed up Q&A from skype chat with Pedro.

**Comment by ZenSpiders** [comment]
Added pictures to Image/PedroSkypeImages still waiting on more images from Pedro. But were supposed to get more images and information and this is reflected in #12
