### ISSUE TITLE
Get an e-mail list for members.

### ISSUE THREAD

**Issue by tamarum** [cclrobotics/lhr-docs#13]
Find a way to make an e-mail list. Preferably through git, if not through the counter culture google group.

**Comment by PatrikD** [comment]
There already is a ccl-robotics google group

**Comment by griswaldbrooks** [comment]
:+1:

**Comment by tamarum** [comment]
We are now using the google group to e-mail members. 
https://groups.google.com/forum/#!forum/ccl-robotics
